"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    # Local apps
    "core",
    "accounts",
    "oauth",
    "repositories",
    "projects",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "core.middleware.RequestIDMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Custom user model — section 6 (email-only identifier)
AUTH_USER_MODEL = "accounts.User"


# REST framework — section 9 (offset pagination), section 10 (JWT auth)
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_PAGINATION_CLASS": "core.pagination.StandardLimitOffsetPagination",
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler",
    "PAGE_SIZE": 20,
}


# SimpleJWT — section 10 (15-min access, 14-day refresh, rotation + blacklist)
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}


# CORS — Vite dev server origin (override via env in production)
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.environ.get("CORS_ALLOWED_ORIGINS", "http://localhost:5173").split(",") if o.strip()
]
CORS_ALLOW_CREDENTIALS = True


# Token-at-rest encryption — section 5 (Fernet)
FERNET_KEY = os.environ["FERNET_KEY"]


# OAuth client credentials — section 5 (client secrets live in env, never in DB or source)
GOOGLE_OAUTH = {
    "CLIENT_ID": os.environ.get("GOOGLE_OAUTH_CLIENT_ID", ""),
    "CLIENT_SECRET": os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET", ""),
    "REDIRECT_URI": os.environ.get("GOOGLE_OAUTH_REDIRECT_URI", ""),
}

GITHUB_OAUTH = {
    "CLIENT_ID": os.environ.get("GITHUB_OAUTH_CLIENT_ID", ""),
    "CLIENT_SECRET": os.environ.get("GITHUB_OAUTH_CLIENT_SECRET", ""),
    "REDIRECT_URI": os.environ.get("GITHUB_OAUTH_REDIRECT_URI", ""),
    # section 8: full repo scope (private + public) + read:user
    "SCOPES": ["read:user", "repo"],
}


# SPA target for post-callback redirect (OAUTH_FLOW.md §6 — fragment delivery)
SPA_AUTH_COMPLETE_URL = os.environ.get(
    "SPA_AUTH_COMPLETE_URL",
    "http://localhost:5173/auth/complete",
)


# Refresh cookie config (OAUTH_FLOW.md §10) — overridable for prod
REFRESH_COOKIE = {
    "NAME": "refresh_token",
    "PATH": "/api/v1/auth/",
    "SECURE": os.environ.get("REFRESH_COOKIE_SECURE", "False").lower() == "true",
    "SAMESITE": os.environ.get("REFRESH_COOKIE_SAMESITE", "Strict"),
    "DOMAIN": os.environ.get("REFRESH_COOKIE_DOMAIN") or None,
}


# Bounded first-page sync (plan.md §7) — keeps in-request sync predictable
GITHUB_SYNC = {
    "MAX_PAGES": int(os.environ.get("GITHUB_SYNC_MAX_PAGES", "5")),
    "PER_PAGE": int(os.environ.get("GITHUB_SYNC_PER_PAGE", "100")),
}


# OAuth state-cookie config (signed, short-lived, per-request)
OAUTH_STATE_COOKIE = {
    "NAME": "oauth_state",
    "PATH": "/api/v1/oauth/",
    "SECURE": os.environ.get("REFRESH_COOKIE_SECURE", "False").lower() == "true",
    "SAMESITE": "Lax",  # must be Lax — provider redirect is a cross-site GET
    "TTL_SECONDS": 600,
}
