# Generated by Django 6.0.5 on 2026-05-16 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="githubprofile",
            name="scopes",
        ),
        migrations.RemoveField(
            model_name="googleprofile",
            name="refresh_token_encrypted",
        ),
        migrations.RemoveField(
            model_name="googleprofile",
            name="scopes",
        ),
        migrations.RemoveField(
            model_name="googleprofile",
            name="token_expires_at",
        ),
    ]
