# Generated by Django 6.0.5 on 2026-05-15 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("oauth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_repo_id", models.BigIntegerField()),
                ("name", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=512)),
                ("private", models.BooleanField(default=False)),
                ("default_branch", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("html_url", models.URLField()),
                ("github_created_at", models.DateTimeField(blank=True, null=True)),
                ("github_pushed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "github_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to="oauth.githubprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Repositories",
                "ordering": ["-github_pushed_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("github_profile", "github_repo_id"),
                        name="unique_repo_per_github_profile",
                    )
                ],
            },
        ),
    ]
